runtime: nodejs20

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
  
- url: /ads.txt
  static_files: ads.txt
  upload: ads.txt
  
- url: /(.*)
  static_files: index.htm
  upload: index.htm
  mime_type: text/html; charset=UTF-8
